version: "3"

services:
    app:
        build:
            context: .
        ports:
            - "5000:5000"
        volumes:
            - ./app:/app
        command: >
            sh -c "python manage.py migrate &&
                   python manage.py runserver 0.0.0.0:5000"
        environment:
            - DB_HOST=db
            - DB_NAME=app
            - DB_USER=admin
            - DB_PASS=password
        depends_on:
            - db

    db:
        image: postgres:10-alpine
        environment:
            - POSTGRES_DB=app
            - POSTGRES_USER=admin
            - POSTGRES_PASSWORD=password